name: Build package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node v${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: Setup UV
      uses: astral-sh/setup-uv@v5.4.2

    - run: |
        npm run build --if-present
        
        whl_file=$(find dist/ -name "*.whl" -print -quit)
        base_name=$(echo "${whl_file}" | cut -d"." -f 2)

        unzip "${whl_file}" -d temp
        
        dist_info=$(find temp/ -name "*.dist-info" -print -quit)
        rm -fr "temp/${dist_info}"

        zip -r "${base_name}.zip" temp/

    - name: Upload release zip
      uses: actions/upload-artifact@v4.6.2
      with:
        name: release
        path: "*.zip"

    - name: Upload source archive
      uses: actions/upload-artifact@v4.6.2
      with:
        name: sdist
        path: "dist/*.tar.gz"

    - name: Upload Python wheel
      uses: actions/upload-artifact@v4.6.2
      with:
        name: wheel
        path: "dist/*.whl"
