name: Build package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Load cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.10

      - name: Prepare artifacts
        if: runner.os == 'Windows'
        run: |
          bun install
          bun run build-release
          
          mkdir release
          mkdir release/dist
          
          cp target/release/conductor.exe release/
          cp dist/payload.template.js release/dist/

      - name: Prepare artifacts
        if: runner.os == 'Linux'
        run: |
          bun install
          bun run build-release
          
          mkdir release
          mkdir release/dist
          
          cp target/release/conductor release/
          cp dist/payload.template.js release/dist/

      - name: Upload release zip
        uses: actions/upload-artifact@v4.6.2
        with:
          name: "release"
          path: "release"