name: Build package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on:
      - ubuntu-latest
      - windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Load cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.10

      - name: Setup UV
        uses: astral-sh/setup-uv@v5.4.2

      - name: Prepare artifacts
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            export EXE_PATH="target/release/conductor.exe"
          else
            export EXE_PATH="target/release/conductor"
          fi
          
          bun install
          bun run build-release
          
          mkdir release
          
          cp $EXE_PATH release
          cp dist/payload.template.js release/dist

      - name: Upload release zip
        uses: actions/upload-artifact@v4.6.2
        with:
          name: "release"
          path: "release"