name: Build package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.10
      
    - name: Setup UV
      uses: astral-sh/setup-uv@v5.4.2

    - run: |
        bun run build --if-present
        
        whl_file=$(find dist/ -name "*.whl" -print -quit)
        base_name=$(echo "${whl_file}" | cut -d"." -f 2)

        unzip "${whl_file}" -d temp
        
        dist_info=$(find temp/ -name "*.dist-info" -print -quit)
        rm -fr "temp/${dist_info}"

        zip -r "${base_name}.zip" temp/

    - name: Upload release zip
      uses: actions/upload-artifact@v4.6.2
      with:
        name: release
        path: "*.zip"

    - name: Upload source archive
      uses: actions/upload-artifact@v4.6.2
      with:
        name: sdist
        path: "dist/*.tar.gz"

    - name: Upload Python wheel
      uses: actions/upload-artifact@v4.6.2
      with:
        name: wheel
        path: "dist/*.whl"
